export const clients = [
       {
              id:1,
              image:require("./assets/clientsdb/clients1.png"),
       },
       {
              id:2,
              image:require("./assets/clientsdb/clients2.png"),
       },
       {
              id:3,
              image:require("./assets/clientsdb/clients3.png"),
       },
       {
              id:4,
              image:require("./assets/clientsdb/clients1.png"),
       },
       {
              id:5,
              image:require("./assets/clientsdb/clients2.png"),
       },
       {
              id:6,
              image:require("./assets/clientsdb/clients3.png"),
       },
       {
              id:7,
              image:require("./assets/clientsdb/clients1.png"),
       },

]