export const sliderdb = [
  {
    id: 1,
    img: require("./assets/images/lr-1750.png"),
    name: "Гусеничный кран Liebherr LR 1750",
    tonna: "40 тонн",
    metr: "35m",
    btn: "Арендовать",
  },
  {
    id: 2,
    img: require("./assets/images/lr-1750.png"),
    name: "Гусеничный кран Liebherr LR 1750",
    tonna: "40 тонн",
    metr: "35m",
    btn: "Арендовать",
  },
  {
    id: 3,
    img: require("./assets/images/lr-1750.png"),
    name: "Гусеничный кран Liebherr LR 1750",
    tonna: "40 тонн",
    metr: "35m",
    btn: "Арендовать",
  },
  {
    id: 4,
    img: require("./assets/images/lr-1750.png"),
    name: "Гусеничный кран Liebherr LR 1750",
    tonna: "40 тонн",
    metr: "35m",
    btn: "Арендовать",
  },
  {
    id: 5,
    img: require("./assets/images/lr-1750.png"),
    name: "Гусеничный кран Liebherr LR 1750",
    tonna: "40 тонн",
    metr: "35m",
    btn: "Арендовать",
  },
  {
    id: 6,
    img: require("./assets/images/lr-1750.png"),
    name: "Гусеничный кран Liebherr LR 1750",
    tonna: "40 тонн",
    metr: "35m",
    btn: "Арендовать",
  },
  {
    id: 7,
    img: require("./assets/images/lr-1750.png"),
    name: "Гусеничный кран Liebherr LR 1750",
    tonna: "40 тонн",
    metr: "35m",
    btn: "Арендовать",
  },
];
