export const sliderdb = [
  {
    id: 1,
    img: require("./assets/images/lr-1750.png"),
    name: "Гусеничный кран Liebherr LR 1750",
    tonna: "40 тонн",
    metr: "35m",
    btn: "Арендовать1",
  },
  {
    id: 2,
    img: require("./assets/images/lr-1750.png"),
    name: "Гусеничный кран Liebherr LR 1750",
    tonna: "40 тонн",
    metr: "35m",
    btn: "Арендовать2",
  },
  {
    id: 3,
    img: require("./assets/images/lr-1750.png"),
    name: "Гусеничный кран Liebherr LR 1750",
    tonna: "40 тонн",
    metr: "35m",
    btn: "Арендовать3",
  },
  {
    id: 4,
    img: require("./assets/images/lr-1750.png"),
    name: "Гусеничный кран Liebherr LR 1750",
    tonna: "40 тонн",
    metr: "35m",
    btn: "Арендовать4",
  },
  {
    id: 5,
    img: require("./assets/images/lr-1750.png"),
    name: "Гусеничный кран Liebherr LR 1750",
    tonna: "40 тонн",
    metr: "35m",
    btn: "Арендовать5",
  },
  {
    id: 6,
    img: require("./assets/images/lr-1750.png"),
    name: "Гусеничный кран Liebherr LR 1750",
    tonna: "40 тонн",
    metr: "35m",
    btn: "Арендовать6",
  },
  {
    id: 7,
    img: require("./assets/images/lr-1750.png"),
    name: "Гусеничный кран Liebherr LR 1750",
    tonna: "40 тонн",
    metr: "35m",
    btn: "Арендовать7",
  },
  {
    id: 8,
    img: require("./assets/images/lr-1750.png"),
    name: "Гусеничный кран Liebherr LR 1750",
    tonna: "40 тонн",
    metr: "35m",
    btn: "Арендовать8",
  },
  {
    id: 9,
    img: require("./assets/images/lr-1750.png"),
    name: "Гусеничный кран Liebherr LR 1750",
    tonna: "40 тонн",
    metr: "35m",
    btn: "Арендовать9",
  },
  {
    id: 10,
    img: require("./assets/images/lr-1750.png"),
    name: "Гусеничный кран Liebherr LR 1750",
    tonna: "40 тонн",
    metr: "35m",
    btn: "Арендовать10",
  },
  {
    id: 11,
    img: require("./assets/images/lr-1750.png"),
    name: "Гусеничный кран Liebherr LR 1750",
    tonna: "40 тонн",
    metr: "35m",
    btn: "Арендовать11",
  },
  {
    id: 12,
    img: require("./assets/images/lr-1750.png"),
    name: "Гусеничный кран Liebherr LR 1750",
    tonna: "40 тонн",
    metr: "35m",
    btn: "Арендовать12",
  },
  {
    id: 13,
    img: require("./assets/images/lr-1750.png"),
    name: "Гусеничный кран Liebherr LR 1750",
    tonna: "40 тонн",
    metr: "35m",
    btn: "Арендовать13",
  },
  {
    id: 14,
    img: require("./assets/images/lr-1750.png"),
    name: "Гусеничный кран Liebherr LR 1750",
    tonna: "40 тонн",
    metr: "35m",
    btn: "Арендовать14",
  },
  {
    id: 15,
    img: require("./assets/images/lr-1750.png"),
    name: "Гусеничный кран Liebherr LR 1750",
    tonna: "40 тонн",
    metr: "35m",
    btn: "Арендовать15",
  },
  {
    id: 16,
    img: require("./assets/images/lr-1750.png"),
    name: "Гусеничный кран Liebherr LR 1750",
    tonna: "40 тонн",
    metr: "35m",
    btn: "Арендовать16",
  },
  {
    id: 17,
    img: require("./assets/images/lr-1750.png"),
    name: "Гусеничный кран Liebherr LR 1750",
    tonna: "40 тонн",
    metr: "35m",
    btn: "Арендовать17",
  },
  {
    id: 18,
    img: require("./assets/images/lr-1750.png"),
    name: "Гусеничный кран Liebherr LR 1750",
    tonna: "40 тонн",
    metr: "35m",
    btn: "Арендовать18",
  },
];
